Remove redundant explicit link target in documentation (#88)
When the CI tries to generate the documentation, it fails with

    error: redundant explicit link target
    Error:    --> dotenv/src/lib.rs:218:51
        |
    218 | /// Loads environment variables from [`io::Read`](std::io::Read).
        |                                       ----------  ^^^^^^^^^^^^^ explicit target is redundant
        |                                       |
        |                                       because label contains path that resolves to same destination
        |
        = note: when a link's destination is not specified,
                the label is used to resolve intra-doc links
        = note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(rustdoc::redundant_explicit_links)]`
    help: remove explicit link target
        |
    218 | /// Loads environment variables from [`io::Read`].
        |                                      ~~~~~~~~~~~~

    error: redundant explicit link target

All instances of this redundant link target are fixed.